title: madmb-blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "madmb"
  email: "madmb@outlook.es"
  url: "https://madmb.github.io/archive"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "madmb"
year : "2022"
